(() => {
  // Shared copy: English fallback, Simplified Chinese, Traditional Chinese.
  const translations = {
    "timeline_present": ["Present", "现在", "現在"],
    "timeline_exploration": ["Endless exploration, endless growth.", "无限探索，无限进步。", "無限探索，無限進步。"],
    "timeline_title": ["On My Way | Yuhua Luo", "On My Way | Yuhua Luo", "On My Way | Yuhua Luo"],
    "timeline_description": ["Personal timeline of Yuhua Luo.", "Yuhua Luo 的个人时间轴。", "Yuhua Luo 的個人時間軸。"],
    "timeline_heading": ["On My Way", "On My Way", "On My Way"],
    "timeline_bilingual_school": ["Shanghai International Studies University Bilingual School", "上海外国语大学附属双语学校", "上海外國語大學附屬雙語學校"],
    "timeline_primary": ["Primary School", "小学", "小學"],
    "timeline_middle": ["Middle School", "初中", "初中"],
    "timeline_high_school": ["High School Affiliated to Shanghai Jiao Tong University", "上海交通大学附属中学", "上海交通大學附屬中學"],
    "timeline_high_school_level": ["High School", "高中", "高中"],
    "timeline_college": ["Undergraduate Studies", "本科学习", "本科學習"],
    "timeline_sjtu_ai": ["School of Artificial Intelligence, Shanghai Jiao Tong University", "上海交通大学人工智能学院", "上海交通大學人工智能學院"],
    "timeline_gaokao": ["Gaokao (National College Entrance Examination)", "高考", "高考"],
    "timeline_summer_school": ["2026 Summer School on Reinforcement Learning", "2026强化学习暑期学校", "2026強化學習暑期學校"],
    "timeline_innovation_institute": ["Shanghai Innovation Institute", "上海创智学院", "上海創智學院"],
    "timeline_gaokao_result": ["617 / 660 · Shanghai Rank #67", "617 / 660 · 上海第 67 名", "617 / 660 · 上海第 67 名"],
    "timeline_rank_prefix": ["617 / 660 · Shanghai Rank #", "617 / 660 · 上海第 ", "617 / 660 · 上海第 "],
    "timeline_rank_suffix": ["", " 名", " 名"],
    "timeline_subjects": ["Physics · Chemistry · Geography", "物理 · 化学 · 地理", "物理 · 化學 · 地理"],
    "timeline_sjtu": ["Shanghai Jiao Tong University", "上海交通大学", "上海交通大學"],
    "timeline_ai_school": ["School of Artificial Intelligence", "人工智能学院", "人工智能學院"],
    "timeline_monitor": ["Class Monitor of the First Undergraduate Cohort", "人工智能学院首届本科生班长", "人工智能學院首屆本科生班長"],
    "timeline_talk": ["Hosted my first talk on science and technology innovation", "首次举办科技创新主题讲座", "首次舉辦科技創新主題講座"],
    "timeline_merit": ["Merit Student", "三好学生", "三好學生"],
    "timeline_league": ["Outstanding League Member", "优秀共青团员", "優秀共青團員"],
    "yuhua_luo_an_ai_undergraduate_at_shanghai_jiao_tong_university_focusing_on_llm": ["Yuhua Luo, an AI undergraduate at Shanghai Jiao Tong University focusing on LLM agents, multi-agent systems and model collaboration.", "Yuhua Luo，上海交通大学人工智能专业本科生，主要研究 LLM Agent、多智能体系统与模型协作。", "Yuhua Luo，上海交通大學人工智能專業本科生，主要研究 LLM Agent、多智能體系統與模型協作。"],
    "skip_to_content": ["Skip to content", "跳转到主要内容", "跳轉到主要內容"],
    "primary_navigation": ["Primary navigation", "主导航", "主導航"],
    "search_this_page": ["Search this page", "搜索本页", "搜索本頁"],
    "search": ["Search", "搜索", "搜索"],
    "search_results": ["Search results", "搜索结果", "搜索結果"],
    "language": ["Language", "语言", "語言"],
    "about": ["About", "关于我", "關於我"],
    "interests": ["Interests", "研究方向", "研究方向"],
    "highlights": ["Highlights", "代表工作", "代表工作"],
    "publications": ["Publications", "论文", "論文"],
    "skills": ["Skills", "技能", "技能"],
    "playground": ["Playground", "Playground", "Playground"],
    "scroll_down_to_about": ["Scroll down to About", "向下滚动至“关于我”", "向下滾動至“關於我”"],
    "scroll_down_for_more": ["Scroll down for more.", "向下滚动查看更多", "向下滾動查看更多"],
    "welcome_to_the_homepage_of": ["Welcome to the homepage of", "欢迎来到个人主页", "歡迎來到個人主頁"],
    "affiliation": ["Shanghai Jiao Tong University, School of Artificial Intelligence", "上海交通大学人工智能学院", "上海交通大學人工智能學院"],
    "summary": ["AI undergraduate focusing on LLM agents, multi-agent systems and model collaboration.", "人工智能专业本科生，主要研究 LLM Agent、多智能体系统与模型协作。", "人工智能專業本科生，主要研究 LLM Agent、多智能體系統與模型協作。"],
    "primary_links": ["Primary links", "主要链接", "主要連結"],
    "academic": ["Academic Background", "学术背景", "學術背景"],
    "introduction": ["I am an undergraduate student in Artificial Intelligence at Shanghai Jiao Tong University, working on language-model systems with a primary focus on LLM agents, multi-agent systems, and model collaboration.", "我是上海交通大学人工智能专业本科生，主要研究大语言模型 Agent、多智能体系统与模型协作。", "我是上海交通大學人工智能專業本科生，主要研究大語言模型 Agent、多智能體系統與模型協作。"],
    "research": ["My research interests center on building capable and adaptive agent systems that can reason, coordinate, and act in complex environments. Recent work spans autonomous agent systems, hierarchical planning and recovery, cross-device interaction, continual learning, and efficient adaptation of large language models.", "我关注 Agent 系统如何在复杂环境中推理、协作和执行任务，并持续适应变化。近期研究包括自主 Agent、分层规划与恢复、跨设备交互、持续学习，以及大语言模型的高效适配。", "我關注 Agent 系統如何在複雜環境中推理、協作和執行任務，並持續適應變化。近期研究包括自主 Agent、分層規劃與恢復、跨裝置互動、持續學習，以及大語言模型的高效適配。"],
    "honors": ["Selected Honors", "部分荣誉", "部分榮譽"],
    "league": ["Outstanding League Member, Shanghai Jiao Tong University", "上海交通大学优秀共青团员", "上海交通大學優秀共青團員"],
    "merit": ["Merit Student, Shanghai Jiao Tong University, 2024-2025", "上海交通大学三好学生，2024–2025 学年", "上海交通大學三好學生，2024–2025 學年"],
    "scholarship": ["Zhiyuan Honor Scholarship, Zhiyuan College, Shanghai Jiao Tong University", "上海交通大学致远学院致远荣誉奖学金", "上海交通大學致遠學院致遠榮譽獎學金"],
    "portrait_of_yuhua_luo": ["Portrait of Yuhua Luo", "Yuhua Luo 的照片", "Yuhua Luo 的照片"],
    "research_interests": ["Research Interests", "研究兴趣", "研究興趣"],
    "topics": ["Topics I Explore", "我关注的方向", "我關注的方向"],
    "research_interests_text": ["Research interests", "研究方向", "研究方向"],
    "autonomous_language_model_agents_can_reason_act_recover_from_failures_and_impr": ["Autonomous language-model agents can reason, act, recover from failures, and improve through interaction and feedback.", "自主语言模型 Agent 可以进行推理和执行，在失败后恢复，并通过交互与反馈持续改进。", "自主語言模型 Agent 可以進行推理和執行，在失敗後恢復，並透過互動與回饋持續改進。"],
    "llm_agents": ["LLM Agents", "LLM Agent", "LLM Agent"],
    "agents": ["Building autonomous language-model agents that reason, act, recover from failures, and improve through interaction and feedback.", "研究大语言模型 Agent 的自主推理、任务执行与失败恢复，以及如何通过交互和反馈持续改进。", "研究大語言模型 Agent 的自主推理、任務執行與失敗恢復，以及如何透過互動和回饋持續改進。"],
    "planning_and_recovery_must_adapt_as_intermediate_states_change_during_long_hor": ["Planning and recovery must adapt as intermediate states change during long-horizon execution.", "在长程任务中，中间状态会不断变化，因此规划与恢复策略也需要随之调整。", "在長程任務中，中間狀態會不斷變化，因此規劃與恢復策略也需要隨之調整。"],
    "planning_recovery_adaptation": ["Planning, Recovery & Adaptation", "规划、恢复与适应", "規劃、恢復與適應"],
    "planning": ["Studying long-horizon planning, execution-time recovery, and adaptive decision-making under changing intermediate states.", "研究 Agent 如何在长程任务中规划行动、从执行失败中恢复，并随任务状态变化调整决策。", "研究 Agent 如何在長程任務中規劃行動、從執行失敗中恢復，並隨任務狀態變化調整決策。"],
    "language_model_reasoning_becomes_more_useful_when_connected_to_heterogeneous_t": ["Language-model reasoning becomes more useful when connected to heterogeneous tools and verifiable execution in real-world environments.", "将语言模型推理与异构工具和可验证的真实环境执行结合，可以让推理真正作用于任务。", "將語言模型推理與異質工具和可驗證的真實環境執行結合，可以讓推理真正作用於任務。"],
    "tool_augmented_reasoning_execution": ["Tool-Augmented Reasoning & Execution", "工具增强的推理与执行", "工具增強的推理與執行"],
    "tools": ["Connecting language-model reasoning with external tools, heterogeneous interfaces, and verifiable execution in real-world environments.", "研究如何将语言模型的推理与外部工具、异构接口结合，让真实环境中的任务执行可靠、可验证。", "研究如何將語言模型的推理與外部工具、異質介面結合，讓真實環境中的任務執行可靠、可驗證。"],
    "cross_device_agent_systems_depend_on_coordination_delegation_and_shared_contex": ["Cross-device agent systems depend on coordination, delegation, and shared context across heterogeneous devices and models.", "跨设备 Agent 系统需要在不同设备和模型之间进行协作、任务分配与上下文共享。", "跨裝置 Agent 系統需要在不同裝置和模型之間進行協作、任務分配與上下文共享。"],
    "multi_agent_cross_device_systems": ["Multi-Agent & Cross-Device Systems", "多智能体与跨设备系统", "多智能體與跨裝置系統"],
    "coordination": ["Exploring coordination, delegation, and shared context across agents, models, and heterogeneous devices.", "研究多个 Agent、模型与异构设备之间的协作、任务分配与上下文共享。", "研究多個 Agent、模型與異質裝置之間的協作、任務分配與上下文共享。"],
    "parameter_efficient_adaptation_and_model_merging_can_add_new_capabilities_whil": ["Parameter-efficient adaptation and model merging can add new capabilities while preserving previously acquired knowledge.", "参数高效适配与模型合并可以在增加新能力的同时尽可能保留已有知识。", "參數高效適配與模型合併可以在增加新能力的同時盡可能保留已有知識。"],
    "continual_learning_model_adaptation": ["Continual Learning & Model Adaptation", "持续学习与模型适配", "持續學習與模型適配"],
    "adaptation": ["Studying how models acquire new capabilities while preserving prior knowledge through parameter-efficient adaptation and model merging.", "研究如何通过参数高效适配与模型合并，让模型掌握新能力，同时尽可能保留已有知识。", "研究如何透過參數高效適配與模型合併，讓模型掌握新能力，同時盡可能保留已有知識。"],
    "continual_and_non_stationary_environments_provide_a_setting_for_studying_how_a": ["Continual and non-stationary environments provide a setting for studying how agents learn, adapt, and retain useful behavior through interaction.", "持续变化的非平稳环境可以用于研究 Agent 如何通过交互学习、适应，并保留有效行为。", "持續變化的非平穩環境可以用於研究 Agent 如何透過互動學習、適應，並保留有效行為。"],
    "reinforcement_learning": ["Reinforcement Learning", "强化学习", "強化學習"],
    "reinforcement": ["Studying how agents learn, adapt, and retain useful behavior through interaction in continual and non-stationary environments.", "研究 Agent 如何在非平稳环境中通过持续交互学习、适应，并保留已学会的有效行为。", "研究 Agent 如何在非平穩環境中透過持續互動學習、適應，並保留已學會的有效行為。"],
    "featured": ["Featured Work & Experience", "代表工作与经历", "代表工作與經歷"],
    "to_be_updated": ["To be updated...", "待更新…", "待更新…"],
    "agent_systems": ["Agent Systems", "Agent 系统", "Agent 系統"],
    "designed_h_replan_a_hierarchical_recovery_framework_that_lets_cross_device_age": ["Designed H-RePlan, a hierarchical recovery framework that lets cross-device agents switch API, CLI, and GUI strategies locally before escalating structured failure evidence to the orchestrator for task or device-level replanning.", "设计 H-RePlan 分层恢复框架，使跨设备 Agent 能够先在设备内切换 API、CLI 和 GUI 等执行策略；局部恢复失败后，再将结构化故障证据上报给编排器，进行任务级或设备级重规划。", "設計 H-RePlan 分層恢復框架，使跨裝置 Agent 能夠先在裝置內切換 API、CLI 和 GUI 等執行策略；局部恢復失敗後，再將結構化故障證據上報給編排器，進行任務級或裝置級重規劃。"],
    "long_horizon": ["Long-Horizon", "长程任务", "長程任務"],
    "recovery": ["Recovery", "恢复", "恢復"],
    "cross_device": ["Cross-Device", "跨设备", "跨裝置"],
    "llm_continual_learning_research": ["LLM Continual Learning Research", "LLM 持续学习研究", "LLM 持續學習研究"],
    "llm_adaptation": ["LLM Adaptation", "LLM 适配", "LLM 適配"],
    "investigated_parameter_efficient_continual_learning_for_language_models_throug": ["Investigated parameter-efficient continual learning for language models through replay-free LoRA composition, task-vector structure, and shared/private parameter decomposition for balancing transfer and task isolation.", "研究面向语言模型的参数高效持续学习，重点关注无需回放的 LoRA 组合、任务向量结构，以及共享/私有参数分解，以平衡知识迁移与任务隔离。", "研究面向語言模型的參數高效持續學習，重點關注無需回放的 LoRA 組合、任務向量結構，以及共享/私有參數分解，以平衡知識遷移與任務隔離。"],
    "continual_learning": ["Continual Learning", "持续学习", "持續學習"],
    "task_vectors": ["Task Vectors", "任务向量", "任務向量"],
    "dynamic_network_widening_for_continual_reinforcement_learning": ["Dynamic Network Widening for Continual Reinforcement Learning", "持续强化学习中的动态网络扩宽", "持續強化學習中的動態網路擴寬"],
    "rl_research": ["RL Research", "强化学习研究", "強化學習研究"],
    "studied_network_capacity_and_mid_training_model_expansion_under_hidden_environ": ["Studied network capacity and mid-training model expansion under hidden environment drift using matched PPO experiments, implementing controlled dynamic widening and evaluating held-out robustness under equal interaction budgets.", "研究隐藏环境漂移下的网络容量与训练中期模型扩展，通过配置匹配的 PPO 实验实现受控的动态扩宽，并在相同交互预算下评估留出环境上的鲁棒性。", "研究隱藏環境漂移下的網路容量與訓練中期模型擴展，透過配置匹配的 PPO 實驗實現受控的動態擴寬，並在相同互動預算下評估留出環境上的魯棒性。"],
    "dynamic_network_growth": ["Dynamic Network Growth", "动态网络扩展", "動態網路擴展"],
    "robustness_evaluation": ["Robustness Evaluation", "鲁棒性评估", "魯棒性評估"],
    "multi_device_agent_orchestration_verified_execution": ["Multi-Device Agent Orchestration & Verified Execution", "多设备 Agent 编排与可验证执行", "多裝置 Agent 編排與可驗證執行"],
    "developed_a_multi_device_agent_system_for_capability_aware_task_orchestration": ["Developed a multi-device agent system for capability-aware task orchestration and reliable execution across heterogeneous devices, integrating API, CLI, and GUI interfaces with execution contracts, evidence collection, and postcondition verification.", "开发面向异构设备的多设备 Agent 系统，根据设备能力进行任务编排，并将 API、CLI 和 GUI 接口与执行契约、证据采集和后置条件验证结合起来，提高任务执行的可靠性。", "開發面向異質裝置的多裝置 Agent 系統，根據裝置能力進行任務編排，並將 API、CLI 和 GUI 介面與執行契約、證據採集和後置條件驗證結合起來，提高任務執行的可靠性。"],
    "multi_agent_systems": ["Multi-Agent Systems", "多智能体系统", "多智能體系統"],
    "agent_orchestration": ["Agent Orchestration", "Agent 编排", "Agent 編排"],
    "tool_use": ["Tool Use", "工具使用", "工具使用"],
    "verified_execution": ["Verified Execution", "可验证执行", "可驗證執行"],
    "view_more": ["View more", "查看更多", "查看更多"],
    "manuscripts": ["Preprints & Manuscripts", "发表论文", "發表論文"],
    "arxiv_preprint_2026": ["arXiv preprint, 2026", "arXiv 预印本，2026", "arXiv 預印本，2026"],
    "hierarchical_recovery_for_cross_device_agents_enabling_local_interface_level_a": ["Hierarchical recovery for cross-device agents, enabling local interface-level adaptation before orchestrator-level replanning.", "面向跨设备 Agent 的分层恢复方法：在进行编排层重规划之前，优先在设备内完成接口级策略调整。", "面向跨裝置 Agent 的分層恢復方法：在進行編排層重規劃之前，優先在裝置內完成介面級策略調整。"],
    "unpublished_manuscript": ["Unpublished manuscript", "未公开论文稿", "未公開論文稿"],
    "details_temporarily_hidden": ["Details temporarily hidden", "详细信息暂未公开", "詳細資訊暫未公開"],
    "stack": ["Technical Stack", "技术栈", "技術棧"],
    "deep_learning_adaptation": ["Deep Learning & Adaptation", "深度学习与模型适配", "深度學習與模型適配"],
    "learning": ["PyTorch, Transformers, PEFT, and PPO for LLM fine-tuning, continual adaptation, model merging, reinforcement learning, and controlled ablation studies.", "使用 PyTorch、Transformers、PEFT 和 PPO 进行 LLM 微调、持续适配、模型合并、强化学习与消融实验。", "使用 PyTorch、Transformers、PEFT 和 PPO 進行 LLM 微調、持續適配、模型合併、強化學習與消融實驗。"],
    "systems": ["LLM agents for long-horizon planning, hierarchical recovery, multi-device orchestration, and reliable execution across API, CLI, and GUI interfaces.", "构建面向长程规划、分层恢复与多设备编排的 LLM Agent 系统，通过 API、CLI 和 GUI 接口可靠地执行任务。", "構建面向長程規劃、分層恢復與多裝置編排的 LLM Agent 系統，透過 API、CLI 和 GUI 介面可靠地執行任務。"],
    "retrieval_knowledge_systems": ["Retrieval & Knowledge Systems", "检索与知识系统", "檢索與知識系統"],
    "retrieval": ["ChromaDB, FAISS, SentenceTransformers, and multilingual embedding models for evidence-grounded retrieval, knowledge-base construction, document pipelines, and source-traceable RAG.", "使用 ChromaDB、FAISS、SentenceTransformers 与多语言 embedding 模型搭建知识库和文档处理流程，支持基于证据的检索与来源可追溯的 RAG。", "使用 ChromaDB、FAISS、SentenceTransformers 與多語言 embedding 模型建立知識庫和文件處理流程，支援基於證據的檢索與來源可追溯的 RAG。"],
    "systems_research_engineering": ["Systems & Research Engineering", "系统与科研工程", "系統與科研工程"],
    "engineering": ["Linux, Git, CUDA, and GPU-based workflows for reproducible experimentation, environment isolation, checkpoint management, parallel execution, and experiment orchestration.", "基于 Linux、Git 和 CUDA 组织 GPU 实验，通过环境隔离、checkpoint 管理、并行执行与实验编排，支持实验复现。", "基於 Linux、Git 和 CUDA 組織 GPU 實驗，透過環境隔離、checkpoint 管理、平行執行與實驗編排，支援實驗重現。"],
    "evaluation_experimental_design": ["Evaluation & Experimental Design", "评估与实验设计", "評估與實驗設計"],
    "evaluation": ["Controlled experiments, ablations, held-out evaluation, multi-seed analysis, failure injection, and postcondition-based verification, supported by Pandas, NumPy, and scikit-learn.", "注重实验条件控制，通过消融实验、留出集评估、多随机种子分析、故障注入和基于后置条件的验证来评估系统，并使用 Pandas、NumPy 和 scikit-learn 分析实验结果。", "注重實驗條件控制，透過消融實驗、留出集評估、多隨機種子分析、故障注入和基於後置條件的驗證來評估系統，並使用 Pandas、NumPy 和 scikit-learn 分析實驗結果。"],
    "beyond": ["Beyond Research", "研究之外", "研究之外"],
    "photo_collection": ["Photo Collection", "照片集", "照片集"],
    "photography": ["Photography", "摄影", "攝影"],
    "photographs": ["Photographs of everyday moments, places, and details.", "用照片记录日常生活中的瞬间、地方和细节。", "用照片記錄日常生活中的瞬間、地方和細節。"],
    "view_photos": ["View Photos", "查看照片", "查看照片"],
    "mods_azx777": ["Mods · AZX777", "Mod · AZX777", "Mod · AZX777"],
    "mods": ["Custom liveries, vehicle unlocks and a new rival crew for Night Runners.", "为 Night Runners 制作 Mod，包括自定义涂装、车辆解锁功能和新的对手车队。", "為 Night Runners 製作 Mod，包括自訂塗裝、車輛解鎖功能和新的對手車隊。"],
    "view_mods": ["View Mods", "查看 Mod", "查看 Mod"],
    "nexus_mods_profile": ["Nexus Mods Profile", "Nexus Mods 主页", "Nexus Mods 主頁"],
    "falling_pulse_rhythm_game": ["Falling Pulse", "Falling Pulse", "Falling Pulse"],
    "interactive_game": ["Interactive Game", "交互式游戏", "交互式遊戲"],
    "game": ["A configurable browser-based fixed-lane falling-note game prototype.", "一款可配置的浏览器固定轨道下落式音符游戏原型。", "一款可設定的瀏覽器固定軌道下落式音符遊戲原型。"],
    "play_demo": ["Play Demo", "试玩 Demo", "試玩 Demo"],
    "open_index_html_source_preview": ["Open index.html source preview", "打开 index.html 源码预览", "打開 index.html 源碼預覽"],
    "azx777_6_mods": ["AZX777 · 6 Mods", "AZX777 · 6 个 Mod", "AZX777 · 6 個 Mod"],
    "close_mod_collection": ["Close mod collection", "关闭 Mod 列表", "關閉 Mod 列表"],
    "midnight_monarchs_cover_artwork_with_rival_cars_and_crew_portraits": ["Midnight Monarchs cover artwork with rival cars and crew portraits", "Midnight Monarchs 封面：多辆对手车辆与车队角色立绘", "Midnight Monarchs 封面：多輛對手車輛與車隊角色立繪"],
    "rival_crew": ["Rival Crew", "对手车队", "對手車隊"],
    "replaces_g_company_with_a_new_mt_haruna_rival_crew_bringing_new_opponents_cars": ["Replaces G-COMPANY with a new Mt. Haruna rival crew, bringing new opponents, cars, portraits and race-based progression.", "用新的榛名山对手车队替换 G-COMPANY，加入全新对手、车辆、角色立绘和基于比赛推进的进度内容。", "用新的榛名山對手車隊替換 G-COMPANY，加入全新對手、車輛、角色立繪和基於比賽推進的進度內容。"],
    "view_on_nexus_mods": ["View on Nexus Mods", "在 Nexus Mods 上查看", "在 Nexus Mods 上查看"],
    "a_collage_of_vehicles_available_with_the_ultimate_unlocker": ["A collage of vehicles available with the ULTIMATE Unlocker", "ULTIMATE Unlocker 可解锁车辆拼图", "ULTIMATE Unlocker 可解鎖車輛拼圖"],
    "vehicle_unlock": ["Vehicle Unlock", "车辆解锁", "車輛解鎖"],
    "expands_the_private_alpha_roster_with_the_360_rx_7_fd_skyline_pgc10_r32_r33_r3": ["Expands the Private Alpha roster with the 360, RX-7 FD, Skyline PGC10/R32/R33/R34, 180SX, NSX NA1 and 964.", "扩充 Private Alpha 的可用车辆阵容，加入 360、RX-7 FD、Skyline PGC10/R32/R33/R34、180SX、NSX NA1 和 964。", "擴充 Private Alpha 的可用車輛陣容，加入 360、RX-7 FD、Skyline PGC10/R32/R33/R34、180SX、NSX NA1 和 964。"],
    "a_lineup_of_korschen_k6_variants": ["A lineup of Korschen K6 variants", "多款 Korschen K6 车型排列展示", "多款 Korschen K6 車型排列展示"],
    "opens_up_korschen_k6_variants_including_turbo_flatnose_and_gemballa_for_purcha": ["Opens up Korschen K6 variants, including Turbo, Flatnose and Gemballa, for purchase, driving and customization.", "开放 Korschen K6 的多种车型版本，包括 Turbo、Flatnose 和 Gemballa，可购买、驾驶并进行自定义。", "開放 Korschen K6 的多種車型版本，包括 Turbo、Flatnose 和 Gemballa，可購買、駕駛並進行自訂。"],
    "180sx_with_a_white_and_orange_racing_livery": ["180SX with a white and orange racing livery", "带白橙赛车涂装的 180SX", "帶白橙賽車塗裝的 180SX"],
    "makes_the_180sx_available_to_purchase_drive_and_customize_in_the_private_alpha": ["Makes the 180SX available to purchase, drive and customize in the Private Alpha.", "让 180SX 在 Private Alpha 中可购买、驾驶和自定义。", "讓 180SX 在 Private Alpha 中可購買、駕駛和自訂。"],
    "flame_graphics_along_a_dark_jzx100_mark_ii": ["Flame graphics along a dark JZX100 Mark II", "深色 JZX100 Mark II 车身上的火焰图案", "深色 JZX100 Mark II 車身上的火焰圖案"],
    "livery": ["Livery", "涂装", "塗裝"],
    "a_drift_inspired_flame_design_for_the_jzx100_mark_ii": ["A drift-inspired flame design for the JZX100 Mark II.", "为 JZX100 Mark II 制作的一套漂移风格火焰涂装。", "為 JZX100 Mark II 製作的一套漂移風格火焰塗裝。"],
    "kita_ikuyo_artwork_on_the_side_of_a_red_200sx": ["Kita Ikuyo artwork on the side of a red 200SX", "红色 200SX 车侧的喜多郁代主题图案", "紅色 200SX 車側的喜多郁代主題圖案"],
    "a_kita_ikuyo_themed_itasha_livery_for_the_200sx": ["A Kita Ikuyo-themed itasha livery for the 200SX.", "为 200SX 制作的喜多郁代主题痛车涂装。", "為 200SX 製作的喜多郁代主題痛車塗裝。"],
    "azx777_on_nexus_mods": ["AZX777 on Nexus Mods", "在 Nexus Mods 查看 AZX777", "在 Nexus Mods 查看 AZX777"],
    "close": ["Close", "关闭", "關閉"],
    "before_playing": ["Before Playing", "游玩前提示", "遊玩前提示"],
    "fixed_lane_rhythm_game_experience": ["Fixed-Lane Rhythm Game Experience?", "您玩过固定轨下落式音游吗？", "您玩過固定軌下落式音遊嗎？"],
    "are_you_a_fixed_lane_rhythm_game_player_or_do_you_have_experience_with_fixed_l": ["Are you a fixed-lane rhythm game player, or do you have experience with fixed-lane rhythm games? If not, you may not know how this demo is played or how its settings work, which could lead to a poor experience.", "您是否玩过固定轨下落式音游，或有类似游戏经验？如果没有，您可能会不熟悉这个 Demo 的玩法和设置方式，从而难以获得好的游戏体验。", "您是否玩過固定軌下落式音遊，或有類似遊戲經驗？如果沒有，您可能會不熟悉這個 Demo 的玩法和設定方式，從而難以獲得好的遊戲體驗。"],
    "yes": ["Yes", "有", "有"],
    "no": ["No", "没有", "沒有"],
    "index_html_source_preview": ["index.html source preview", "index.html 源码预览", "index.html 源碼預覽"],
    "close_source_preview": ["Close source preview", "关闭源码预览", "關閉源碼預覽"],
    "nav_skills": ["Skills", "技术栈", "技術棧"],
    "selected_academic_and_applied_ai_work_by_yuhua_luo": ["Selected academic and applied AI work by Yuhua Luo.", "Yuhua Luo 的代表性学术研究与 AI 应用项目。", "Yuhua Luo 的代表性學術研究與 AI 應用項目。"],
    "featured_work_yuhua_luo": ["Featured Work | Yuhua Luo", "代表工作 | Yuhua Luo", "代表工作 | Yuhua Luo"],
    "home": ["Home", "首页", "首頁"],
    "featured_work": ["Featured Work", "代表工作", "代表工作"],
    "projects_and_research": ["Projects and Research", "项目与研究", "項目與研究"],
    "selected_research_major_projects": ["Selected Research / Major Projects", "代表性研究 / 主要项目", "代表性研究 / 主要項目"],
    "designed_and_implemented_h_replan_a_hierarchical_replanning_framework_for_cros": ["Designed and implemented H-RePlan, a hierarchical replanning framework for cross-device agents that separates device-local strategy recovery from orchestrator-level task and device reassignment.", "设计并实现 H-RePlan 分层重规划框架，将跨设备 Agent 的设备内策略恢复与编排层的任务和设备重新分配分离。", "設計並實現 H-RePlan 分層重規劃框架，將跨裝置 Agent 的裝置內策略恢復與編排層的任務和裝置重新分配分離。"],
    "added_an_llm_based_strategy_planner_that_selects_and_retries_api_cli_and_gui_e": ["Added an LLM-based strategy planner that selects and retries API, CLI, and GUI execution strategies within each device context.", "加入基于 LLM 的策略规划器，在每个设备上下文中选择并重试 API、CLI 和 GUI 执行策略。", "加入基於 LLM 的策略規劃器，在每個裝置上下文中選擇並重試 API、CLI 和 GUI 執行策略。"],
    "introduced_cross_layer_failure_events_clfes_to_compress_local_execution_eviden": ["Introduced Cross-Layer Failure Events (CLFEs) to compress local execution evidence into structured signals for orchestration-level replanning.", "提出 Cross-Layer Failure Events（CLFE），将设备内执行证据压缩为结构化信号，供编排层重规划使用。", "提出 Cross-Layer Failure Events（CLFE），將裝置內執行證據壓縮為結構化信號，供編排層重規劃使用。"],
    "integrated_capability_aware_strategy_bindings_retry_budgets_chain_history_and": ["Integrated capability-aware strategy bindings, retry budgets, chain history, and partial DAG-result reuse into the MDC/UFO³ execution flow.", "在 MDC/UFO³ 执行流程中集成能力感知的策略绑定、重试预算、执行链历史以及 DAG 部分结果复用。", "在 MDC/UFO³ 執行流程中集成能力感知的策略綁定、重試預算、執行鏈歷史以及 DAG 部分結果複用。"],
    "built_herabench_fault_injection_workflows_over_linux_and_android_devices_cover": ["Built HeraBench fault-injection workflows over Linux and Android devices, covering local, global, and mixed failures across 174 task variants.", "在 Linux 与 Android 设备上构建 HeraBench 故障注入流程，覆盖 174 个任务变体中的局部、全局和混合故障。", "在 Linux 與 Android 裝置上構建 HeraBench 故障注入流程，覆蓋 174 個任務變體中的局部、全局和混合故障。"],
    "paper": ["Paper", "论文", "論文"],
    "investigated_parameter_efficient_continual_learning_for_language_models_focusi": ["Investigated parameter-efficient continual learning for language models, focusing on replay-free LoRA composition, task-vector structure, and shared/private parameter decomposition.", "研究面向语言模型的参数高效持续学习，重点关注无需回放的 LoRA 组合、任务向量结构，以及共享/私有参数分解。", "研究面向語言模型的參數高效持續學習，重點關注無需回放的 LoRA 組合、任務向量結構，以及共享/私有參數分解。"],
    "analyzed_lora_updates_as_task_vectors_and_studied_how_task_specific_changes_ap": ["Analyzed LoRA updates as task vectors and studied how task-specific changes appear in parameter space.", "将 LoRA 更新视为任务向量，分析不同任务带来的参数变化在参数空间中的结构。", "將 LoRA 更新視為任務向量，分析不同任務帶來的參數變化在參數空間中的結構。"],
    "explored_geometry_aware_decomposition_between_transferable_shared_components_a": ["Explored geometry-aware decomposition between transferable shared components and task-private residuals.", "探索可迁移共享分量与任务私有残差之间的几何结构分解。", "探索可遷移共享分量與任務私有殘差之間的幾何結構分解。"],
    "built_continual_learning_experiment_workflows_across_multiple_text_classificat": ["Built continual-learning experiment workflows across multiple text-classification task sequences.", "围绕多组文本分类任务序列搭建持续学习实验流程。", "圍繞多組文本分類任務序列搭建持續學習實驗流程。"],
    "organized_training_logs_metric_aggregation_and_ablation_records_for_reproducib": ["Organized training logs, metric aggregation, and ablation records for reproducible comparison.", "整理训练日志、指标汇总和消融实验记录，支持可复现比较。", "整理訓練日誌、指標匯總和消融實驗記錄，支援可重現比較。"],
    "conducted_a_reproducible_continual_control_study_on_network_capacity_and_mid_t": ["Conducted a reproducible continual-control study on network capacity and mid-training model expansion under hidden environment drift. Designed matched PPO experiments across multiple network widths, implemented controlled dynamic widening, and evaluated learning efficiency and held-out robustness under equal interaction budgets.", "围绕隐藏环境漂移下的网络容量与训练中期模型扩展开展可复现的持续控制研究。在多个网络宽度上设计配置匹配的 PPO 实验，实现受控的动态扩宽，并在相同交互预算下评估学习效率与留出环境上的鲁棒性。", "圍繞隱藏環境漂移下的網路容量與訓練中期模型擴展開展可重現的持續控制研究。在多個網路寬度上設計配置匹配的 PPO 實驗，實現受控的動態擴寬，並在相同互動預算下評估學習效率與留出環境上的魯棒性。"],
    "constructed_a_continually_changing_cartpole_environment_with_hidden_gravity_ma": ["Constructed a continually changing CartPole environment with hidden gravity, mass, pole length, force, and friction perturbations.", "构建持续变化的 CartPole 环境，对重力、质量、杆长、作用力和摩擦进行隐藏扰动。", "構建持續變化的 CartPole 環境，對重力、質量、桿長、作用力和摩擦進行隱藏擾動。"],
    "matched_ppo_configurations_and_interaction_budgets_across_network_widths_using": ["Matched PPO configurations and interaction budgets across network widths, using multiple training seeds and held-out evaluation panels.", "在不同网络宽度间保持 PPO 配置与交互预算一致，并使用多个训练随机种子和留出评估环境进行比较。", "在不同網路寬度間保持 PPO 配置與互動預算一致，並使用多個訓練隨機種子和留出評估環境進行比較。"],
    "compared_fixed_width_policies_with_64_128_mid_training_widening_under_default": ["Compared fixed-width policies with 64→128 mid-training widening under default and literal all-zero initialization.", "比较固定宽度策略与训练中期 64→128 动态扩宽，并分别测试默认初始化和严格全零初始化。", "比較固定寬度策略與訓練中期 64→128 動態擴寬，並分別測試預設初始化和嚴格全零初始化。"],
    "built_a_reproducibility_pipeline_that_preserved_configurations_checkpoints_rng": ["Built a reproducibility pipeline that preserved configurations, checkpoints, RNG and environment states, selection records, plots, and evaluation tables.", "搭建可复现实验流程，保存配置、checkpoint、随机数生成器与环境状态、模型选择记录、图表及评估表格。", "搭建可重現實驗流程，保存配置、checkpoint、隨機數生成器與環境狀態、模型選擇記錄、圖表及評估表格。"],
    "developed_a_multi_device_agent_system_for_capability_aware_task_orchestration_text": ["Developed a multi-device agent system for capability-aware task orchestration and reliable execution across heterogeneous devices, combining interface abstraction, execution evidence, and explicit verification of real-world task outcomes.", "开发面向异构设备的多设备 Agent 系统，根据设备能力进行任务编排，并结合接口抽象、执行证据与真实任务结果的显式验证，提高执行可靠性。", "開發面向異質裝置的多裝置 Agent 系統，根據裝置能力進行任務編排，並結合介面抽象、執行證據與真實任務結果的顯式驗證，提高執行可靠性。"],
    "designed_capability_aware_orchestration_for_assigning_tasks_to_devices_and_exe": ["Designed capability-aware orchestration for assigning tasks to devices and execution interfaces suited to each environment.", "设计能力感知的任务编排，根据设备环境将任务分配给合适的设备与执行接口。", "設計能力感知的任務編排，根據裝置環境將任務分配給合適的裝置與執行介面。"],
    "unified_api_cli_and_gui_operations_behind_structured_execution_interfaces_with": ["Unified API, CLI, and GUI operations behind structured execution interfaces with device-adaptive tool selection.", "通过结构化执行接口统一 API、CLI 和 GUI 操作，并根据设备环境选择合适的工具。", "透過結構化執行介面統一 API、CLI 和 GUI 操作，並根據裝置環境選擇合適的工具。"],
    "defined_execution_contracts_that_connect_expected_outputs_collected_evidence_a": ["Defined execution contracts that connect expected outputs, collected evidence, and postconditions instead of treating raw tool success as task completion.", "定义执行契约，将预期输出、采集证据与后置条件关联起来，不再把工具调用成功直接视为任务完成。", "定義執行契約，將預期輸出、採集證據與後置條件關聯起來，不再把工具調用成功直接視為任務完成。"],
    "built_system_evaluation_workflows_for_cross_device_execution_tracking_interfac": ["Built system-evaluation workflows for cross-device execution, tracking interface behavior, completion evidence, and end-state correctness.", "搭建跨设备系统评估流程，跟踪接口行为、完成证据与最终状态是否正确。", "搭建跨裝置系統評估流程，跟蹤介面行為、完成證據與最終狀態是否正確。"],
    "telecom_customer_service_intent_recognition": ["Telecom Customer Service Intent Recognition", "电信客服意图识别", "電信客服意圖識別"],
    "applied_ai_systems": ["Applied AI Systems", "应用 AI 系统", "應用 AI 系統"],
    "developed_a_dialogue_understanding_pipeline_for_long_multi_turn_telecom_servic": ["Developed a dialogue-understanding pipeline for long, multi-turn telecom service sessions, combining intent recognition, target-plan prediction, structured plan knowledge, retrieval, and LoRA/SFT experimentation.", "开发面向长多轮电信客服会话的对话理解流程，结合意图识别、目标套餐预测、结构化套餐知识、检索以及 LoRA/SFT 实验。", "開發面向長多輪電信客服會話的對話理解流程，結合意圖識別、目標套餐預測、結構化套餐知識、檢索以及 LoRA/SFT 實驗。"],
    "cleaned_aggregated_and_labeled_1_405_multi_turn_customer_service_sessions_for": ["Cleaned, aggregated, and labeled 1,405 multi-turn customer service sessions for intent and plan-related analysis.", "清洗、聚合并标注 1,405 段多轮客服会话，用于意图与套餐相关分析。", "清洗、聚合併標註 1,405 段多輪客服會話，用於意圖與套餐相關分析。"],
    "converted_telecom_plan_information_into_retrievable_candidate_knowledge_for_do": ["Converted telecom plan information into retrievable candidate knowledge for downstream reasoning.", "将电信套餐信息整理为可检索的候选知识，供后续推理使用。", "將電信套餐資訊整理為可檢索的候選知識，供後續推理使用。"],
    "designed_a_rag_plus_few_shot_workflow_that_conditions_on_user_plans_candidate": ["Designed a RAG plus few-shot workflow that conditions on user plans, candidate plans, and dialogue context.", "设计 RAG + few-shot 流程，综合用户当前套餐、候选套餐与对话上下文进行判断。", "設計 RAG + few-shot 流程，綜合用戶當前套餐、候選套餐與對話上下文進行判斷。"],
    "ran_lora_sft_experiments_on_open_source_7b_models_and_compared_them_with_basel": ["Ran LoRA/SFT experiments on open-source 7B models and compared them with baseline settings.", "在开源 7B 模型上开展 LoRA/SFT 实验，并与基线设置进行比较。", "在開源 7B 模型上開展 LoRA/SFT 實驗，並與基線設定進行比較。"],
    "few_shot_reasoning": ["Few-shot Reasoning", "Few-shot 推理", "Few-shot 推理"],
    "dialogue_understanding": ["Dialogue Understanding", "对话理解", "對話理解"],
    "ai4ms_medical_knowledge_graph_rag_system": ["AI4MS Medical Knowledge Graph & RAG System", "AI4MS 医疗知识图谱与 RAG 系统", "AI4MS 醫療知識圖譜與 RAG 系統"],
    "knowledge_systems": ["Knowledge Systems", "知识系统", "知識系統"],
    "built_a_local_evidence_grounded_qa_prototype_for_multiple_sclerosis_knowledge": ["Built a local evidence-grounded QA prototype for multiple sclerosis knowledge organization, combining document parsing, vector retrieval, source traceability, and knowledge-graph style structuring.", "构建本地、基于证据的多发性硬化症问答原型，将文档解析、向量检索、来源追踪与知识图谱式组织结合起来。", "構建本地、基於證據的多發性硬化症問答原型，將文件解析、向量檢索、來源追蹤與知識圖譜式組織結合起來。"],
    "parsed_and_organized_multi_source_medical_materials_into_searchable_knowledge": ["Parsed and organized multi-source medical materials into searchable knowledge assets.", "解析并整理多来源医学资料，构建可检索的知识资源。", "解析並整理多來源醫學資料，構建可檢索的知識資源。"],
    "indexed_evidence_chunks_with_chromadb_and_multilingual_minilm_embeddings_for_l": ["Indexed evidence chunks with ChromaDB and multilingual MiniLM embeddings for local retrieval.", "使用 ChromaDB 与多语言 MiniLM embedding 对证据片段建立本地索引。", "使用 ChromaDB 與多語言 MiniLM embedding 對證據片段建立本地索引。"],
    "mapped_user_questions_to_relevant_source_passages_through_source_aware_retriev": ["Mapped user questions to relevant source passages through source-aware retrieval.", "通过可追溯来源的检索，将用户问题映射到相关原文片段。", "透過可追溯來源的檢索，將用戶問題映射到相關原文片段。"],
    "preserved_citations_and_evidence_links_to_reduce_unsupported_answer_generation": ["Preserved citations and evidence links to reduce unsupported answer generation.", "保留引用与证据链接，减少缺乏依据的回答生成。", "保留引用與證據連結，減少缺乏依據的回答生成。"],
    "knowledge_graph": ["Knowledge Graph", "知识图谱", "知識圖譜"],
    "medical_rag": ["Medical RAG", "医疗 RAG", "醫療 RAG"],
    "other_projects_reproductions": ["Other Projects & Reproductions", "其他项目与复现", "其他項目與重現"],
    "training_aware_agent_research": ["Training-aware Agent Research", "结合训练信号的 Agent 研究", "結合訓練信號的 Agent 研究"],
    "studying_training_aware_agent_systems_that_connect_learning_signals_with_plann": ["Studying training-aware agent systems that connect learning signals with planning, memory, tool use, and replanning, with emphasis on long-horizon execution and adaptive behavior.", "研究如何将训练信号与规划、记忆、工具使用和重规划结合到 Agent 系统中，重点关注长程执行和自适应行为。", "研究如何將訓練信號與規劃、記憶、工具使用和重規劃結合到 Agent 系統中，重點關注長程執行和自適應行為。"],
    "tracked_recent_work_on_self_improving_agents_agentic_reinforcement_learning_an": ["Tracked recent work on self-improving agents, agentic reinforcement learning, and tool-augmented workflows.", "跟踪自改进 Agent、Agentic RL 和工具增强工作流等近期研究。", "跟蹤自改進 Agent、Agentic RL 和工具增強工作流程等近期研究。"],
    "studied_planning_and_replanning_mechanisms_as_core_components_for_robust_long": ["Studied planning and replanning mechanisms as core components for robust long-horizon execution.", "研究规划与重规划机制在鲁棒长程执行中的作用。", "研究規劃與重規劃機制在魯棒長程執行中的作用。"],
    "prepared_technical_notes_to_organize_assumptions_design_patterns_and_experimen": ["Prepared technical notes to organize assumptions, design patterns, and experiment directions.", "整理技术笔记，系统记录假设、设计模式和实验方向。", "整理技術筆記，系統記錄假設、設計模式和實驗方向。"],
    "focused_on_how_training_signals_could_shape_agent_behavior_beyond_static_promp": ["Focused on how training signals could shape agent behavior beyond static prompting.", "关注训练信号如何让 Agent 的行为超越静态提示。", "關注訓練信號如何讓 Agent 的行為超越靜態提示。"],
    "memory": ["Memory", "记忆", "記憶"],
    "style_aware_humanoid_motion_generation": ["Style-Aware Humanoid Motion Generation", "风格感知的人形运动生成", "風格感知的人形運動生成"],
    "embodied_ai": ["Embodied AI", "具身智能", "具身智能"],
    "built_a_project_layer_around_moconvq_for_style_aware_language_conditioned_huma": ["Built a project layer around MoConVQ for style-aware, language-conditioned humanoid motion generation, emphasizing reproducible generation scripts, structured prompts, and diagnostic reporting.", "基于 MoConVQ 搭建风格感知、语言条件的人形运动生成流程，重点关注生成脚本的可复现性、结构化提示词和诊断报告。", "基於 MoConVQ 搭建風格感知、語言條件的人形運動生成流程，重點關注生成腳本的可重現性、結構化提示詞和診斷報告。"],
    "prepared_style_lexicons_prompt_lists_audit_templates_and_humanml3d_derived_sty": ["Prepared style lexicons, prompt lists, audit templates, and HumanML3D-derived style subsets.", "整理风格词表、提示词列表、审计模板和基于 HumanML3D 构建的风格子集。", "整理風格詞表、提示詞列表、審計模板和基於 HumanML3D 構建的風格子集。"],
    "organized_baseline_generation_adapter_training_evaluation_and_report_compilati": ["Organized baseline generation, adapter training, evaluation, and report-compilation scripts.", "组织基线生成、adapter 训练、评估和报告汇总脚本。", "組織基線生成、adapter 訓練、評估和報告匯總腳本。"],
    "packaged_midterm_and_final_deliverables_with_logs_outputs_and_reproducibility": ["Packaged midterm and final deliverables with logs, outputs, and reproducibility notes.", "整理期中与最终交付材料，包括日志、输出结果和复现说明。", "整理期中與最終交付材料，包括日誌、輸出結果和重現說明。"],
    "documented_runtime_asset_limitations_and_avoided_unsupported_metric_claims_in": ["Documented runtime asset limitations and avoided unsupported metric claims in the report.", "在报告中明确记录运行时资源限制，并避免给出缺乏依据的指标结论。", "在報告中明確記錄運行時資源限制，並避免給出缺乏依據的指標結論。"],
    "motion_generation": ["Motion Generation", "运动生成", "運動生成"],
    "reproducibility": ["Reproducibility", "可复现性", "可重現性"],
    "snapkv_kv_cache_compression_reproduction": ["SnapKV KV Cache Compression Reproduction", "SnapKV KV Cache 压缩复现", "SnapKV KV Cache 壓縮重現"],
    "inference_systems": ["Inference Systems", "推理系统", "推理系統"],
    "reproduced_the_snapkv_training_free_kv_cache_compression_method_and_evaluated": ["Reproduced the SnapKV training-free KV cache compression method and evaluated its latency, memory, and perplexity behavior in small-scale LLM inference settings.", "复现 SnapKV 无需训练的 KV Cache 压缩方法，并在小规模 LLM 推理场景中评估其延迟、内存占用和困惑度表现。", "重現 SnapKV 無需訓練的 KV Cache 壓縮方法，並在小規模 LLM 推理場景中評估其延遲、記憶體占用和困惑度表現。"],
    "implemented_post_prefill_kv_cache_compression_with_observation_window_scoring": ["Implemented post-prefill KV cache compression with observation-window scoring and pooling.", "实现 prefill 后的 KV Cache 压缩，采用观察窗口打分与 pooling。", "實現 prefill 後的 KV Cache 壓縮，採用觀察窗口打分與 pooling。"],
    "compared_baseline_and_compressed_inference_on_wikitext_and_pg_19_workloads": ["Compared baseline and compressed inference on WikiText and PG-19 workloads.", "在 WikiText 和 PG-19 工作负载上比较基线与压缩后的推理表现。", "在 WikiText 和 PG-19 工作負載上比較基線與壓縮後的推理表現。"],
    "recorded_ttft_tpot_throughput_peak_memory_flops_and_perplexity_related_metrics": ["Recorded TTFT, TPOT, throughput, peak memory, FLOPs, and perplexity-related metrics.", "记录 TTFT、TPOT、吞吐量、峰值显存、FLOPs 以及与 perplexity 相关的指标。", "記錄 TTFT、TPOT、吞吐量、峰值顯示記憶體、FLOPs 以及與 perplexity 相關的指標。"],
    "ran_ablations_over_compression_ratio_observation_window_size_and_pooling_kerne": ["Ran ablations over compression ratio, observation-window size, and pooling kernel size.", "针对压缩比例、观察窗口大小和 pooling 核大小开展消融实验。", "針對壓縮比例、觀察窗口大小和 pooling 核大小開展消融實驗。"],
    "llm_inference": ["LLM Inference", "LLM 推理", "LLM 推理"],
    "natdedprop_proof_agent_and_tooling": ["NatDedProp Proof Agent and Tooling", "NatDedProp 证明 Agent 与工具链", "NatDedProp 證明 Agent 與工具鏈"],
    "formal_reasoning": ["Formal Reasoning", "形式化推理", "形式化推理"],
    "packaged_a_natural_deduction_proof_workflow_with_command_line_checking_vs_code": ["Packaged a natural-deduction proof workflow with command-line checking, VS Code tooling, reusable proof prompts, and logged answer-generation diagnostics.", "将自然演绎证明流程封装为完整工具链，包含命令行检查、VS Code 工具、可复用证明提示词以及回答生成诊断日志。", "將自然演繹證明流程封裝為完整工具鏈，包含命令行檢查、VS Code 工具、可複用證明提示詞以及回答生成診斷日誌。"],
    "prepared_a_self_contained_natdedprop_environment_with_command_line_checker_and": ["Prepared a self-contained NatDedProp environment with command-line checker and VS Code extension packages.", "准备自包含的 NatDedProp 环境，包含命令行检查器与 VS Code 扩展包。", "準備自包含的 NatDedProp 環境，包含命令行檢查器與 VS Code 擴展包。"],
    "designed_a_proof_agent_workflow_for_diagnosing_mmd_files_and_replacing_proof_p": ["Designed a proof-agent workflow for diagnosing `.mmd` files and replacing proof placeholders.", "设计证明 Agent 工作流，用于诊断 `.mmd` 文件并替换证明占位符。", "設計證明 Agent 工作流程，用於診斷 `.mmd` 文件並替換證明占位符。"],
    "encoded_connective_driven_strategies_for_conjunction_disjunction_implication_e": ["Encoded connective-driven strategies for conjunction, disjunction, implication, equivalence, and classical tautologies.", "针对合取、析取、蕴含、等价和经典重言式，编码由逻辑联结词驱动的证明策略。", "針對合取、析取、蘊含、等價和經典重言式，編碼由邏輯聯結詞驅動的證明策略。"],
    "recorded_diagnostics_proof_attempts_checker_results_and_packaging_events_in_js": ["Recorded diagnostics, proof attempts, checker results, and packaging events in JSONL logs.", "以 JSONL 记录诊断信息、证明尝试、检查器结果和打包事件。", "以 JSONL 記錄診斷資訊、證明嘗試、檢查器結果和打包事件。"],
    "formal_proof": ["Formal Proof", "形式化证明", "形式化證明"],
    "natural_deduction": ["Natural Deduction", "自然演绎", "自然演繹"],
    "vs_code_extension": ["VS Code Extension", "VS Code 扩展", "VS Code 擴展"],
    "agent_workflow": ["Agent Workflow", "Agent 工作流", "Agent 工作流程"],
    "mods_for": ["Mods for ", "", ""],
    "mods_suffix": ["", " Mod", " Mod"],
    "games_night_runners_mods_and_side_projects_by_yuhua_luo": ["Photography, Night Runners mods, games and apps by Yuhua Luo.", "Yuhua Luo 的摄影、Night Runners Mod、游戏与应用。", "Yuhua Luo 的攝影、Night Runners Mod、遊戲與應用。"],
    "playground_yuhua_luo": ["Playground | Yuhua Luo", "研究之外 | Yuhua Luo", "研究之外 | Yuhua Luo"],
    "miniature_car_photography": ["Miniature car photography", "微缩汽车摄影", "微縮汽車攝影"],
    "miniature_models_summary": ["Miniature cars, photographed with an eye for form, light, and detail.", "用镜头捕捉微缩汽车的造型、光影与细节。", "用鏡頭捕捉微縮汽車的造型、光影與細節。"],
    "previous_photos": ["Previous photos", "上一组照片", "上一組照片"],
    "pause_slideshow": ["Pause slideshow", "暂停轮播", "暫停輪播"],
    "next_photos": ["Next photos", "下一组照片", "下一組照片"],
    "view_all": ["View all", "查看全部", "查看全部"],
    "loading_photos": ["Loading photos...", "正在加载照片…", "正在載入照片…"],
    "reload_photos": ["Reload photos", "重新加载照片", "重新載入照片"],
    "photo_slideshow": ["Photo slideshow", "照片轮播", "照片輪播"],
    "mods_text": ["Mods", "Mod", "Mod"],
    "games": ["Games", "游戏", "遊戲"],
    "for_fun": ["For Fun", "兴趣项目", "興趣項目"],
    "side_projects": ["Side Projects", "个人项目", "個人項目"],
    "side_projects_summary": ["Small games and useful apps I build out of curiosity.", "出于好奇写的小游戏与实用小程序。", "出於好奇寫的小遊戲與實用小程式。"],
    "explore_projects": ["Explore Projects", "探索项目", "探索項目"],
    "off_script": ["Off Script", "自由发挥", "自由發揮"],
    "rhythm_chart_editor": ["Rhythm Chart Editor", "音游制谱工具", "音遊製譜工具"],
    "chartflow_summary": ["A browser-based rhythm chart tool for recording, editing, and playing 4K–8K charts.", "一款浏览器端音游制谱工具，支持 4K–8K 谱面的录入、编辑与试玩。", "一款瀏覽器端音遊製譜工具，支援 4K–8K 譜面的錄入、編輯與試玩。"],
    "chartflow_recording": ["Records keyboard performances on empty lanes and quantizes input to a 1/32 grid.", "在空轨道上录入键盘演奏，并将输入量化到 1/32 网格。", "在空軌道上錄入鍵盤演奏，並將輸入量化到 1/32 網格。"],
    "chartflow_editing": ["Provides a visual editor with note selection, movement, copy and paste, undo and redo, preview, and playtesting.", "提供可视化编辑器，支持音符选择、移动、复制粘贴、撤销重做、预览和试玩。", "提供視覺化編輯器，支援音符選取、移動、複製貼上、復原重做、預覽和試玩。"],
    "chartflow_storage": ["Keeps charts, profiles, and progress in the browser, with JSON import and export for transferring saves.", "谱面、用户资料和进度保存在浏览器本地，可通过 JSON 导入导出迁移存档。", "譜面、使用者資料和進度儲存在瀏覽器本機，可透過 JSON 匯入匯出移轉存檔。"],
    "windows_app": ["Windows App", "Windows 应用", "Windows 應用"],
    "peeker_summary": ["A local-only privacy watcher for Windows that gently alerts you when someone nearby appears to be looking at your screen.", "一款完全在本地运行的 Windows 防窥提醒工具，在身旁有人疑似注视屏幕时轻柔提醒。", "一款完全在本機執行的 Windows 防窺提醒工具，在身旁有人疑似注視螢幕時輕柔提醒。"],
    "peeker_detection": ["Uses face detection and head pose to spot potential onlookers, with a subtle eye alert at the top of the screen.", "结合人脸检测与头部姿态判断潜在旁观者，通过屏幕顶部的小眼睛提示。", "結合人臉偵測與頭部姿態判斷潛在旁觀者，透過螢幕頂部的小眼睛提示。"],
    "peeker_privacy": ["Processes camera frames locally without saving or uploading them.", "摄像头画面仅在本地处理，不保存、不上传。", "攝影機畫面僅在本機處理，不儲存、不上傳。"],
    "peeker_controls": ["Runs in the system tray, with monitoring controls and an optional camera preview.", "常驻系统托盘，可随时开关监测，并按需打开摄像头预览。", "常駐系統匣，可隨時開關監測，並按需開啟攝影機預覽。"],
    "deskveil_summary": ["A Windows app that automatically veils your screens when you step away and reveals them when you return, without locking your computer.", "一款 Windows 应用，离开座位时自动遮住屏幕，回来后自动解除，无需锁定电脑。", "一款 Windows 應用，離開座位時自動遮住螢幕，回來後自動解除，無需鎖定電腦。"],
    "deskveil_cover": ["Uses face detection to trigger a frosted-glass overlay across all monitors during short breaks.", "通过人脸检测判断离开状态，在短暂离开时为所有显示器覆盖磨砂玻璃遮罩。", "透過人臉偵測判斷離開狀態，在短暫離開時為所有顯示器覆蓋磨砂玻璃遮罩。"],
    "deskveil_privacy": ["Processes camera and desktop images locally in memory, without saving or uploading them.", "摄像头与桌面画面仅在本地内存中处理，不保存、不上传。", "攝影機與桌面畫面僅在本機記憶體中處理，不儲存、不上傳。"],
    "deskveil_controls": ["Runs in the system tray, with manual cover, a 10-minute snooze, and a keyboard shortcut to dismiss the overlay.", "常驻系统托盘，支持手动遮屏、暂停 10 分钟，以及快捷键解除遮罩。", "常駐系統匣，支援手動遮屏、暫停 10 分鐘，以及快捷鍵解除遮罩。"],
    "download_for_windows": ["Download for Windows", "下载 Windows 版", "下載 Windows 版"],
    "view_on_github": ["View on GitHub", "在 GitHub 查看", "在 GitHub 查看"],
    "implemented_adjustable_bpm_scroll_speed_difficulty_note_count_beat_divisions_a": ["Implemented adjustable BPM, scroll speed, difficulty, note count, beat divisions, and 4K/5K/6K lane modes.", "支持可调 BPM、流速、难度、物量、音符分拍，以及 4K/5K/6K 轨道模式。", "支援可調 BPM、流速、難度、物量、音符分拍，以及 4K/5K/6K 軌道模式。"],
    "added_profile_customization_rating_progression_achievements_key_bindings_autop": ["Features profile customization, rating progression, achievements, key bindings, autoplay, and metronome controls.", "提供玩家资料自定义、Rating 成长、成就、键位绑定、Autoplay 和节拍器控制。", "提供玩家資料自訂、Rating 成長、成就、鍵位綁定、Autoplay 和節拍器控制。"],
    "falling_pulse_simulator": ["A rhythm-game-style simulator with no music, only beats, designed to train players' reaction speed and sight-reading ability.", "一款没有音乐、只有节拍的音游式模拟器，旨在训练玩家的反应速度和读谱能力。", "一款沒有音樂、只有節拍的音遊式模擬器，旨在訓練玩家的反應速度和讀譜能力。"],
    "rhythm_game": ["Rhythm Game", "音游", "音遊"],
    "input_timing": ["Input Timing", "输入时序", "輸入時序"],
    "back_to_homepage": ["Back to homepage", "返回主页", "返回主頁"],
    "all_photos": ["All photos", "全部照片", "全部照片"],
    "open_original_photo": ["Open original photo", "打开原图", "打開原圖"],
    "open_original": ["Open original", "打开原图", "打開原圖"],
    "close_photo_viewer": ["Close photo viewer", "关闭照片查看器", "關閉照片查看器"],
    "previous_photo": ["Previous photo", "上一张照片", "上一張照片"],
    "next_photo": ["Next photo", "下一张照片", "下一張照片"],
    "playground_game": ["A configurable browser-based fixed-lane falling-note game prototype.", "一款可配置的浏览器固定轨道下落式音符游戏原型。", "一款可設定的瀏覽器固定軌道下落式音符遊戲原型。"],
    "section": ["Section", "栏目", "欄目"],
    "no_matching_section": ["No matching section", "未找到匹配内容", "未找到匹配內容"],
    "local_preview_required": ["Local preview required", "需要通过本地服务器预览", "需要透過本地伺服器預覽"],
    "photo_library_temporarily_unavailable": ["Photo library temporarily unavailable", "照片库暂时不可用", "照片庫暫時不可用"],
    "photo_library_unavailable": ["Photo library unavailable", "无法加载照片库", "無法載入照片庫"],
    "photo_library_index_is_incomplete": ["Photo library index is incomplete", "照片库索引不完整", "照片庫索引不完整"],
    "open_photo_title": ["Open photo: {title}", "打开照片：{title}", "打開照片：{title}"],
    "unavailable_photo_title": ["Unavailable photo: {title}", "照片不可用：{title}", "照片不可用：{title}"],
    "original_unavailable_showing_preview": ["Original unavailable. Showing preview.", "原图暂不可用，当前显示预览图。", "原圖暫不可用，當前顯示預覽圖。"],
    "preparing_photos": ["Preparing photos...", "正在准备照片…", "正在準備照片…"],
    "photos_ready": ["Photos ready", "照片已加载", "照片已載入"],
    "no_photos_yet": ["No photos yet", "暂无照片", "暫無照片"],
    "photo_library_timed_out": ["Photo library timed out", "加载照片库超时", "載入照片庫超時"],
    "resume_slideshow": ["Resume slideshow", "继续轮播", "繼續輪播"],
    "image_unavailable": ["Image unavailable", "图片不可用", "圖片不可用"],
    "programming_languages": ["Languages", "编程语言", "編程語言"],
    "languages": ["Python and C++ for research prototyping, LLM and RL experimentation, data pipelines, and systems-oriented engineering.", "主要使用 Python 和 C++ 开发研究原型、运行 LLM 与强化学习实验、搭建数据处理流程，并进行相关系统开发。", "主要使用 Python 和 C++ 開發研究原型、運行 LLM 與強化學習實驗、搭建資料處理流程，並進行相關系統開發。"],
    "last_synced": ["Last synced: 2026.9", "最近同步：2026.9", "最近同步：2026.9"],
  };

  const supported = ["en", "zh-Hans", "zh-Hant"];
  const attributes = { "aria-label": "aria-label", title: "title", placeholder: "placeholder", tooltip: "data-tooltip", content: "content", alt: "alt", "error-label": "data-error-label" };
  // Keep original HTML values, including whitespace, for exact English restoration.
  // Dynamic bindings retain their key/variables so an in-flight status can be translated too.
  const originals = new WeakMap();
  let language = "en";
  const interpolate = (text, vars) => text.replace(/\{(\w+)\}/g, (match, name) => vars[name] ?? match);
  const t = (key, vars = {}, fallback = key) => {
    const entry = translations[key];
    return interpolate(entry?.[supported.indexOf(language)] ?? entry?.[0] ?? fallback, vars);
  };
  const binding = (element, target, key) => {
    if (element.closest('[translate="no"]')) return;
    let values = originals.get(element);
    if (!values) { values = new Map(); originals.set(element, values); }
    if (!values.has(target)) values.set(target, {
      english: target === "text" ? element.textContent : element.getAttribute(target), vars: {},
    });
    const { english, vars } = values.get(target);
    const value = language === "en" ? interpolate(english ?? "", vars) : t(key, vars, english ?? "");
    if (target === "text") element.textContent = value;
    else element.setAttribute(target, value);
  };
  const set = (element, target, key, vars = {}) => {
    let values = originals.get(element);
    if (!values) { values = new Map(); originals.set(element, values); }
    values.set(target, { english: translations[key]?.[0] ?? key, vars });
    const suffix = target === "text" ? "" : "-" + Object.keys(attributes).find(name => attributes[name] === target);
    element.setAttribute("data-i18n" + suffix, key);
    binding(element, target, key);
  };
  const getSourceText = element => {
    const original = originals.get(element)?.get("text");
    if (original) return original.english;
    return Array.from(element.childNodes, node =>
      node.nodeType === Node.TEXT_NODE ? node.textContent : getSourceText(node)).join("");
  };
  window.siteI18n = {
    t,
    getSourceText,
    get language() { return language; },
    setText: (element, key, vars) => set(element, "text", key, vars),
    setAttribute: (element, attribute, key, vars) => set(element, attribute, key, vars),
  };
  const buttons = [...document.querySelectorAll("[data-language-switcher] [data-language]")];
  const applyLanguage = selected => {
    language = supported.includes(selected) ? selected : "en";
    document.querySelectorAll("[data-i18n]").forEach(element => binding(element, "text", element.dataset.i18n));
    for (const [marker, attribute] of Object.entries(attributes)) {
      document.querySelectorAll(`[data-i18n-${marker}]`).forEach(element =>
        binding(element, attribute, element.getAttribute(`data-i18n-${marker}`)));
    }
    document.documentElement.lang = language;
    buttons.forEach(button => button.setAttribute("aria-pressed", String(button.dataset.language === language)));
    try { localStorage.setItem("site-language", language); } catch { /* Switching still works without storage. */ }
    document.dispatchEvent(new Event("site-language-change"));
  };
  buttons.forEach(button => button.addEventListener("click", () => applyLanguage(button.dataset.language)));
  let initialLanguage = "en";
  try { initialLanguage = localStorage.getItem("site-language") || "en"; } catch { /* Default to English. */ }
  applyLanguage(initialLanguage);
})();
